#!/bin/bash

##
# DEBUG flag
DEBUG="no"

##
# RUN_MODE means how to execute this script
# support for 2 modes, include one time and repeat in X seconds
RUN_MODE="onetime"
#RUN_MODE="repeat"
#RUN_INTERVAL=5

##
# Source and destinadtions
FILES="fcsync.csv"

##
#Remote port number
REMOTE_PORT_NUM="57764"

##
#Target port number
TARGET_PORT_NUM="22"

##
# Move successed files flag, in "yes" or "no"
MOVE_FLAG="yes"

##
# Check file flag
# set this flag 'yes' to enable remote file md5sum check after file transfered
AFTER_CHECK_FLAG="no"

##
# Retry X times if failed
RETRY_IF_FAILED=3
RETRY_IF_FILE_IS_OPENED=3
RETRY_IF_FAILED_SLEEPTIME=5
RETRY_IF_FILE_IS_OPENED_SLEEPTIME=1

##
# LOGS
ERROR_LOG="/data1/bx/fcremote_logs/es1_cs/error.log"
INFO_LOG="/data1/bx/fcremote_logs/es1_cs/info.log"
TOTAL_LOG="/data1/bx/fcremote_logs/es1_cs/total.log"
FAIL_LOG="/data1/bx/fcremote_logs/es1_cs/fail.log"

##
# A csv data1base contains file information:
# SOURCE_FILENAME,DESTINATION,FILE_SIZE,FILE_MTIME,FILE_UPLOADTIME
PROCESS_CSV="status.csv"

##
# A directory stores failed files
FAILED_DIR="/tmp/fails/"

##
# A directory stores successed files
SUCCESSED_DIR="/data1/es_logs2/current/success"
##

# LOCK
# if this file exists, dont run this program
LOCK_FLAG="/tmp/fcsync_es1_cs.lock"

##
# EXIT FLAG FILE
# only works in repeat mode, if this file contents is "abort", then exit this program
ABORT_FLAG="flag"


##
# Remote scripts
LOCAL_SCRIPT_DIR="remote_script"

##
# Remote script dir
REMOTE_SCRIPT_DIR="/run/fcremotesync_script"
